### ISSUE TITLE
Use array.join instead string concatenation for template generation

### ISSUE THREAD

**Issue by StarpTech** [edge-js/parser#1]
Hi, I think the benefit could be huge with less effort at all. This would also require to setup a proper benchmark suite. Are you interested?

Source: https://twitter.com/bmeurer/status/973881345935110144
Proof: https://github.com/Rich-Harris/sourcemap-codec/pull/71/files

**Comment by thetutlage** [comment]
Yes, if it helps in improving performance, then why not? Can you please share a PR for same?

**Comment by StarpTech** [comment]
I will close this issue because after some benchmarks there is no real performance difference. It's very unlikely that someone generates a page with 100000 concatenations.
