### ISSUE TITLE
Object/Array parsing

### ISSUE THREAD

**Issue by velikayikci** [edge-js/parser#18]
Hello,

How can i parse this string to array object ?
{{ [{"column1":"Ali","column2":"Veli","id":1}] }}

const fn = new Function('', `return function template (state, escape, reThrow) { ${output} }`)();
method return [object Object]

**Comment by thetutlage** [comment]
Can you please provide more information. 

- Which package are you using and the version?
- The actual code you have written?
- What error do you get or what is the actual/expected outcome?

Closing for now. Please share more info and we can reopen the issue and discuss more

**Comment by velikayikci** [comment]
I am using exactly in this example code https://github.com/edge-js/parser/blob/develop/example/index.ts  and latest version.

just replace 'Hello {{ username }}' with '{{ [{"column1":"Ali","column2":"Veli","id":1}] }}'  line 22 in index.ts.

the problem username is string but i give an array object.

**Comment by thetutlage** [comment]
Yes because when you convert an array to string you get the output you are getting. Can you please explain what exactly are you trying to do? Do you want to loop over the array or just pretty print it as it is?

**Comment by velikayikci** [comment]
I want the Array object as output
input: "{{ [{"column1":"Ali","column2":"Veli"}] }}" 
expected output: [{"column1":"Ali","column2":"Veli"}]   

so input is a string but the output is an array object.
